{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "union-csi-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "union-csi-driver.labels" . | nindent 4 }}
{{- end }}
