apiVersion: v2
name: union-csi-driver
description: overlayfs and mergerfs CSI driver - unions a pod's sibling volumes into one merged mount
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/Ruakij/union-csi-driver
sources:
  - https://github.com/Ruakij/union-csi-driver
maintainers:
  - name: Ruakij
    url: https://github.com/Ruakij
keywords:
  - csi
  - storage
  - overlayfs
  - overlay
  - mergerfs
  - fuse
  - union
  - unionfs
  - merge
  - ephemeral
annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
